name: The Money Machine Trading Bot

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  trade:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install MetaTrader 5
        timeout-minutes: 5
        shell: powershell
        run: |
          curl.exe -L -o mt5setup.exe "https://download.mql5.com/cdn/web/exness.technologies.ltd/mt5/exness5setup.exe"
          Start-Process -FilePath ".\mt5setup.exe" -ArgumentList "/auto", "/quit" -Wait

      - name: Run Trading Bot
        env:
          MT5_LOGIN: ${{ secrets.MT5_LOGIN }}
          MT5_PASSWORD: ${{ secrets.MT5_PASSWORD }}
          MT5_SERVER: ${{ secrets.MT5_SERVER }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: python main.py
